modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/kyber-6/beings-of-elderia-mod/issues"
license = "MIT"

[[mods]]
modId = "beings_of_elderia"
version = "${version}"
displayName = "Beings of Elderia"
authors = "lwkysad, thrasos, BanditBytes, Pixel Dream Studios"
description = '''
Discover a world where angels soar in the Aether and demons lurk in the Hell. Explore these mystical realms and encounter beings of immense power and ancient lore.
'''
displayURL="https://modrinth.com/mod/beings-of-elderia"
logoFile = "icon.png"

[[dependencies.beings_of_elderia]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beings_of_elderia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beings_of_elderia]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.beings_of_elderia]]
modId = "azurelib"
mandatory = true
versionRange = "[2.0.30,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beings_of_elderia]]
modId = "smartbrainlib"
mandatory = true
versionRange = "[1.14.2,)"
ordering = "NONE"
side = "BOTH"

